#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'

  require_relative "lexer"
  require_relative "nodes"

class Parser < Racc::Parser

module_eval(<<'...end grammar.y/module_eval...', 'grammar.y', 177)
  # This code will be put as-is in the Parser class.
  def parse(code, show_tokens=false)
    @tokens = Lexer.new.tokenize(code) # Tokenize the code using our lexer
    puts @tokens.inspect if show_tokens
    do_parse # Kickoff the parsing process
  end

  def next_token
    @tokens.shift
  end
...end grammar.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    26,    14,    24,    21,    25,    27,    14,    16,    17,    18,
    19,    20,    22,    23,    26,    75,    24,    21,    25,    75,
    14,    16,    17,    18,    19,    20,    22,    23,    43,    15,
    47,    45,    13,    44,    15,    75,    77,    74,    29,    48,
    40,    41,    38,    39,    46,    49,    13,    26,    15,    24,
    21,    25,    51,    83,    16,    17,    18,    19,    20,    22,
    23,    26,    53,    24,    21,    25,    67,    72,    16,    17,
    18,    19,    20,    22,    23,    81,    79,    80,    26,    13,
    24,    21,    25,    29,    29,    16,    17,    18,    19,    20,
    22,    23,    26,    13,    24,    21,    25,    85,    87,    16,
    17,    18,    19,    20,    22,    23,    92,    85,    91,    26,
    13,    24,    21,    25,    75,    75,    16,    17,    18,    19,
    20,    22,    23,    26,    13,    24,    21,    25,    98,    75,
    16,    17,    18,    19,    20,    22,    23,    81,   nil,    95,
    26,    13,    24,    21,    25,   nil,   nil,    16,    17,    18,
    19,    20,    22,    23,    26,    13,    24,    21,    25,   nil,
   nil,    16,    17,    18,    19,    20,    22,    23,    92,   nil,
    96,    26,    13,    24,    21,    25,   nil,   nil,    16,    17,
    18,    19,    20,    22,    23,    26,    13,    24,    21,    25,
   nil,   nil,    16,    17,    18,    19,    20,    22,    23,   nil,
   nil,   nil,    26,    13,    24,    21,    25,   nil,   nil,    16,
    17,    18,    19,    20,    22,    23,    26,    13,    24,    21,
    25,   nil,   nil,    16,    17,    18,    19,    20,    22,    23,
   nil,   nil,   nil,    26,    13,    24,    21,    25,   nil,   nil,
    16,    17,    18,    19,    20,    22,    23,    26,    13,    24,
    21,    25,   nil,   nil,    16,    17,    18,    19,    20,    22,
    23,   nil,   nil,   nil,    26,    13,    24,    21,    25,   nil,
   nil,    16,    17,    18,    19,    20,    22,    23,    26,    13,
    24,    21,    25,   nil,   nil,    16,    17,    18,    19,    20,
    22,    23,   nil,   nil,   nil,    26,    13,    24,    21,    25,
   nil,   nil,    16,    17,    18,    19,    20,    22,    23,    26,
    13,    24,    21,    25,   nil,   nil,    16,    17,    18,    19,
    20,    22,    23,   nil,   nil,   nil,    26,    13,    24,    21,
    25,   nil,   nil,    16,    17,    18,    19,    20,    22,    23,
    26,    13,    24,    21,    25,    14,   nil,    16,    17,    18,
    19,    20,    22,    23,    93,   nil,   nil,    29,    13,    40,
    41,    38,    39,    34,    35,    36,    37,    32,    33,    31,
    30,   nil,    13,    15,    66,    75,   nil,    29,   nil,    40,
    41,    38,    39,    34,    35,    36,    37,    32,    33,    31,
    30,    29,   nil,    40,    41,    38,    39,    34,    35,    36,
    37,    32,    33,    31,    30,    29,   nil,    40,    41,    38,
    39,    34,    35,    36,    37,    32,    33,    31,    30,    29,
   nil,    40,    41,    38,    39,    34,    35,    36,    37,    32,
    33,    31,    30,    29,   nil,    40,    41,    38,    39,    34,
    35,    36,    37,    32,    33,    31,    30,    29,   nil,    40,
    41,    38,    39,    34,    35,    36,    37,    32,    33,    31,
    30,    29,   nil,    40,    41,    38,    39,    34,    35,    36,
    37,    32,    33,    31,    30,    29,   nil,    40,    41,    38,
    39,    34,    35,    36,    37,    32,    33,    31,    29,   nil,
    40,    41,    38,    39,    34,    35,    36,    37,    32,    33,
    29,   nil,    40,    41,    38,    39,    34,    35,    36,    37,
    29,   nil,    40,    41,    38,    39,    34,    35,    36,    37,
    29,   nil,    40,    41,    38,    39,    29,   nil,    40,    41,
    38,    39,    29,   nil,    40,    41,    38,    39,    29,   nil,
    40,    41,    29,   nil,    40,    41 ]

racc_action_check = [
     0,     2,     0,     0,     0,     1,     0,     0,     0,     0,
     0,     0,     0,     0,    75,    49,    75,    75,    75,    48,
    75,    75,    75,    75,    75,    75,    75,    75,    17,     2,
    24,    22,     0,    22,     0,    72,    49,    48,    58,    24,
    58,    58,    58,    58,    23,    25,    75,    13,    75,    13,
    13,    13,    27,    72,    13,    13,    13,    13,    13,    13,
    13,    26,    29,    26,    26,    26,    43,    47,    26,    26,
    26,    26,    26,    26,    26,    68,    53,    68,    28,    13,
    28,    28,    28,    64,    65,    28,    28,    28,    28,    28,
    28,    28,    30,    26,    30,    30,    30,    74,    77,    30,
    30,    30,    30,    30,    30,    30,    84,    83,    84,    31,
    28,    31,    31,    31,    87,    91,    31,    31,    31,    31,
    31,    31,    31,    32,    30,    32,    32,    32,    92,    96,
    32,    32,    32,    32,    32,    32,    32,    88,   nil,    88,
    33,    31,    33,    33,    33,   nil,   nil,    33,    33,    33,
    33,    33,    33,    33,    34,    32,    34,    34,    34,   nil,
   nil,    34,    34,    34,    34,    34,    34,    34,    90,   nil,
    90,    35,    33,    35,    35,    35,   nil,   nil,    35,    35,
    35,    35,    35,    35,    35,    36,    34,    36,    36,    36,
   nil,   nil,    36,    36,    36,    36,    36,    36,    36,   nil,
   nil,   nil,    37,    35,    37,    37,    37,   nil,   nil,    37,
    37,    37,    37,    37,    37,    37,    38,    36,    38,    38,
    38,   nil,   nil,    38,    38,    38,    38,    38,    38,    38,
   nil,   nil,   nil,    39,    37,    39,    39,    39,   nil,   nil,
    39,    39,    39,    39,    39,    39,    39,    40,    38,    40,
    40,    40,   nil,   nil,    40,    40,    40,    40,    40,    40,
    40,   nil,   nil,   nil,    41,    39,    41,    41,    41,   nil,
   nil,    41,    41,    41,    41,    41,    41,    41,    44,    40,
    44,    44,    44,   nil,   nil,    44,    44,    44,    44,    44,
    44,    44,   nil,   nil,   nil,    45,    41,    45,    45,    45,
   nil,   nil,    45,    45,    45,    45,    45,    45,    45,    46,
    44,    46,    46,    46,   nil,   nil,    46,    46,    46,    46,
    46,    46,    46,   nil,   nil,   nil,    79,    45,    79,    79,
    79,   nil,   nil,    79,    79,    79,    79,    79,    79,    79,
    81,    46,    81,    81,    81,    86,   nil,    81,    81,    81,
    81,    81,    81,    81,    86,   nil,   nil,    42,    79,    42,
    42,    42,    42,    42,    42,    42,    42,    42,    42,    42,
    42,   nil,    81,    86,    42,    50,   nil,    50,   nil,    50,
    50,    50,    50,    50,    50,    50,    50,    50,    50,    50,
    50,     3,   nil,     3,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     3,    52,   nil,    52,    52,    52,
    52,    52,    52,    52,    52,    52,    52,    52,    52,    69,
   nil,    69,    69,    69,    69,    69,    69,    69,    69,    69,
    69,    69,    69,    70,   nil,    70,    70,    70,    70,    70,
    70,    70,    70,    70,    70,    70,    70,    71,   nil,    71,
    71,    71,    71,    71,    71,    71,    71,    71,    71,    71,
    71,    89,   nil,    89,    89,    89,    89,    89,    89,    89,
    89,    89,    89,    89,    89,    54,   nil,    54,    54,    54,
    54,    54,    54,    54,    54,    54,    54,    54,    55,   nil,
    55,    55,    55,    55,    55,    55,    55,    55,    55,    55,
    56,   nil,    56,    56,    56,    56,    56,    56,    56,    56,
    57,   nil,    57,    57,    57,    57,    57,    57,    57,    57,
    59,   nil,    59,    59,    59,    59,    60,   nil,    60,    60,
    60,    60,    61,   nil,    61,    61,    61,    61,    62,   nil,
    62,    62,    63,   nil,    63,    63 ]

racc_action_pointer = [
    -2,     5,    -7,   373,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    45,   nil,   nil,   nil,     6,   nil,   nil,
   nil,   nil,    -1,    12,    25,    30,    59,    52,    76,    48,
    90,   107,   121,   138,   152,   169,   183,   200,   214,   231,
   245,   262,   339,    56,   276,   293,   307,    53,     3,    -1,
   359,   nil,   387,    42,   457,   470,   482,   492,    20,   502,
   508,   514,   520,   524,    65,    66,   nil,   nil,    42,   401,
   415,   429,    19,   nil,    83,    12,   nil,    83,   nil,   324,
   nil,   338,   nil,    93,    73,   nil,   337,    98,   104,   443,
   135,    99,   114,   nil,   nil,   nil,   113,   nil,   nil,   nil ]

racc_action_default = [
    -1,   -58,    -2,    -3,    -6,    -7,    -8,    -9,   -10,   -11,
   -12,   -13,   -14,   -58,   -16,   -17,   -18,   -19,   -20,   -21,
   -22,   -23,   -24,   -44,   -58,   -58,   -58,   -58,    -5,   -58,
   -58,   -58,   -58,   -58,   -58,   -58,   -58,   -58,   -58,   -58,
   -58,   -58,   -58,   -58,   -28,   -58,   -58,   -58,   -58,   -58,
   -58,   100,    -4,   -26,   -31,   -32,   -33,   -34,   -35,   -36,
   -37,   -38,   -40,   -41,   -42,   -43,   -15,   -39,   -58,   -29,
   -45,   -46,   -58,   -48,   -51,   -58,   -54,   -58,   -56,   -28,
   -25,   -58,   -47,   -51,   -58,   -52,   -58,   -58,   -58,   -30,
   -58,   -58,   -58,   -57,   -55,   -27,   -58,   -50,   -53,   -49 ]

racc_goto_table = [
    28,     2,    42,    68,    84,     1,   nil,    73,    76,    78,
   nil,   nil,   nil,    90,   nil,    50,   nil,    52,   nil,    54,
    55,    56,    57,    58,    59,    60,    61,    62,    63,    64,
    65,    82,   nil,    69,    70,    71,   nil,   nil,    88,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    94,   nil,   nil,   nil,
    97,   nil,   nil,   nil,   nil,    99,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    69,   nil,
    89,   nil,   nil,   nil,   nil,   nil,    86,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    28 ]

racc_goto_check = [
     4,     2,     3,    13,    15,     1,   nil,    14,    14,    14,
   nil,   nil,   nil,    15,   nil,     3,   nil,     3,   nil,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     3,    14,   nil,     3,     3,     3,   nil,   nil,    13,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    14,   nil,   nil,   nil,
    14,   nil,   nil,   nil,   nil,    14,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     3,   nil,
     3,   nil,   nil,   nil,   nil,   nil,     2,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     4 ]

racc_goto_pointer = [
   nil,     5,     1,   -11,    -2,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   -41,   -41,   -70 ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     5,     6,     7,     8,     9,
    10,    11,    12,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 39, :_reduce_1,
  1, 39, :_reduce_2,
  1, 40, :_reduce_3,
  3, 40, :_reduce_4,
  2, 40, :_reduce_5,
  1, 40, :_reduce_6,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  3, 41, :_reduce_15,
  1, 42, :_reduce_none,
  1, 42, :_reduce_none,
  1, 43, :_reduce_18,
  1, 43, :_reduce_19,
  1, 43, :_reduce_20,
  1, 43, :_reduce_21,
  1, 43, :_reduce_22,
  1, 43, :_reduce_23,
  1, 44, :_reduce_24,
  4, 44, :_reduce_25,
  3, 44, :_reduce_26,
  6, 44, :_reduce_27,
  0, 51, :_reduce_28,
  1, 51, :_reduce_29,
  3, 51, :_reduce_30,
  3, 45, :_reduce_31,
  3, 45, :_reduce_32,
  3, 45, :_reduce_33,
  3, 45, :_reduce_34,
  3, 45, :_reduce_35,
  3, 45, :_reduce_36,
  3, 45, :_reduce_37,
  3, 45, :_reduce_38,
  3, 45, :_reduce_39,
  3, 45, :_reduce_40,
  3, 45, :_reduce_41,
  3, 45, :_reduce_42,
  3, 45, :_reduce_43,
  1, 46, :_reduce_44,
  3, 47, :_reduce_45,
  3, 47, :_reduce_46,
  4, 48, :_reduce_47,
  3, 48, :_reduce_48,
  7, 48, :_reduce_49,
  6, 48, :_reduce_50,
  0, 53, :_reduce_51,
  1, 53, :_reduce_52,
  3, 53, :_reduce_53,
  3, 49, :_reduce_54,
  5, 49, :_reduce_55,
  3, 50, :_reduce_56,
  3, 52, :_reduce_57 ]

racc_reduce_n = 58

racc_shift_n = 100

racc_token_table = {
  false => 0,
  :error => 1,
  :IF => 2,
  :ELSE => 3,
  :DEF => 4,
  :STATIC => 5,
  :CLASS => 6,
  :SELF => 7,
  :NEWLINE => 8,
  :NUMBER => 9,
  :STRING => 10,
  :TRUE => 11,
  :FALSE => 12,
  :NIL => 13,
  :IDENTIFIER => 14,
  :CONSTANT => 15,
  :INDENT => 16,
  :DEDENT => 17,
  "." => 18,
  "!" => 19,
  "*" => 20,
  "/" => 21,
  "+" => 22,
  "-" => 23,
  ">" => 24,
  ">=" => 25,
  "<" => 26,
  "<=" => 27,
  "==" => 28,
  "!=" => 29,
  "&&" => 30,
  "||" => 31,
  "=" => 32,
  "," => 33,
  "(" => 34,
  ")" => 35,
  ";" => 36,
  ":" => 37 }

racc_nt_base = 38

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "IF",
  "ELSE",
  "DEF",
  "STATIC",
  "CLASS",
  "SELF",
  "NEWLINE",
  "NUMBER",
  "STRING",
  "TRUE",
  "FALSE",
  "NIL",
  "IDENTIFIER",
  "CONSTANT",
  "INDENT",
  "DEDENT",
  "\".\"",
  "\"!\"",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "\">\"",
  "\">=\"",
  "\"<\"",
  "\"<=\"",
  "\"==\"",
  "\"!=\"",
  "\"&&\"",
  "\"||\"",
  "\"=\"",
  "\",\"",
  "\"(\"",
  "\")\"",
  "\";\"",
  "\":\"",
  "$start",
  "Root",
  "Expressions",
  "Expression",
  "Terminator",
  "Literal",
  "Call",
  "Operator",
  "Constant",
  "Assign",
  "Def",
  "Class",
  "If",
  "ArgList",
  "Block",
  "ParamList" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'grammar.y', 45)
  def _reduce_1(val, _values, result)
     result = Nodes.new([]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 46)
  def _reduce_2(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 51)
  def _reduce_3(val, _values, result)
     result = Nodes.new(val) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 52)
  def _reduce_4(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 54)
  def _reduce_5(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 55)
  def _reduce_6(val, _values, result)
     result = Nodes.new([]) 
    result
  end
.,.,

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

module_eval(<<'.,.,', 'grammar.y', 68)
  def _reduce_15(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 16 omitted

# reduce 17 omitted

module_eval(<<'.,.,', 'grammar.y', 79)
  def _reduce_18(val, _values, result)
     result = NumberNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 80)
  def _reduce_19(val, _values, result)
     result = StringNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 81)
  def _reduce_20(val, _values, result)
     result = TrueNode.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 82)
  def _reduce_21(val, _values, result)
     result = FalseNode.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 83)
  def _reduce_22(val, _values, result)
     result = NilNode.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 84)
  def _reduce_23(val, _values, result)
     result = StaticNode.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 90)
  def _reduce_24(val, _values, result)
     result = CallNode.new(nil, val[0], []) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 92)
  def _reduce_25(val, _values, result)
     result = CallNode.new(nil, val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 94)
  def _reduce_26(val, _values, result)
     result = CallNode.new(val[0], val[2], []) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 97)
  def _reduce_27(val, _values, result)
     result = CallNode.new(val[0], val[2], val[4]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 101)
  def _reduce_28(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 102)
  def _reduce_29(val, _values, result)
     result = val 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 103)
  def _reduce_30(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 108)
  def _reduce_31(val, _values, result)
     result = OperatorNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 109)
  def _reduce_32(val, _values, result)
     result = OperatorNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 110)
  def _reduce_33(val, _values, result)
     result = OperatorNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 111)
  def _reduce_34(val, _values, result)
     result = OperatorNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 112)
  def _reduce_35(val, _values, result)
     result = OperatorNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 113)
  def _reduce_36(val, _values, result)
     result = OperatorNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 114)
  def _reduce_37(val, _values, result)
     result = OperatorNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 115)
  def _reduce_38(val, _values, result)
     result = OperatorNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 116)
  def _reduce_39(val, _values, result)
     result = StringCmpNode.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 117)
  def _reduce_40(val, _values, result)
     result = OperatorNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 118)
  def _reduce_41(val, _values, result)
     result = OperatorNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 119)
  def _reduce_42(val, _values, result)
     result = OperatorNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 120)
  def _reduce_43(val, _values, result)
     result = OperatorNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 124)
  def _reduce_44(val, _values, result)
     result = GetConstantNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 129)
  def _reduce_45(val, _values, result)
     result = SetLocalNode.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 130)
  def _reduce_46(val, _values, result)
     result = SetConstantNode.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 135)
  def _reduce_47(val, _values, result)
     result = DefNode.new(true, val[2], [], val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 136)
  def _reduce_48(val, _values, result)
     result = DefNode.new(false, val[1], [], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 138)
  def _reduce_49(val, _values, result)
     result = DefNode.new(true, val[2], val[4], val[6])
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 140)
  def _reduce_50(val, _values, result)
     result = DefNode.new(false, val[1], val[3], val[5]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 144)
  def _reduce_51(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 145)
  def _reduce_52(val, _values, result)
     result = val 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 146)
  def _reduce_53(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 151)
  def _reduce_54(val, _values, result)
     result = ClassNode.new(val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 152)
  def _reduce_55(val, _values, result)
     result = SuperClassNode.new(val[1], val[3], val[4]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 157)
  def _reduce_56(val, _values, result)
     result = IfNode.new(val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 163)
  def _reduce_57(val, _values, result)
     result = val[1] 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Parser
